checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  dependencies:
    before:
      - pip install --upgrade pip
      - pip install "setuptools>=43.0.0"
      - pip install importlib-resources
      - pip install poetry==1.1.12
      - poetry config virtualenvs.create false
      - poetry install

  tests:
    override:
      - tox

  nodes:
    py3.6:
      environment:
        python: 3.6.5

    py3.7:
      environment:
        python: 3.7.0

    py3.8:
      environment:
        python: 3.8.0

    py3.9:
      environment:
        python: 3.9.0

    py3.10:
      environment:
        python: 3.10.0

      tests:
        override:
          - tox
          - py-scrutinizer-run
